### ISSUE TITLE
Need exact values

### ISSUE THREAD

**Issue by scaredcat** [bor3ham/mireco#1]
If my landlord asked me to pay the same amount every 4 weeks instead of every month, I would not be impressed.

https://github.com/bor3ham/mireco/blob/cbf1617f55942b5327a274ba232011b67bd8ec16/src/forms/duration.js#L7

**Comment by bor3ham** [comment]
I think this is currently the only sane way to handle months in this context where it has to resolve to a milliseconds value

I'll add it to the list of components to eventually support, some kinda abstract time durations eg months, years.
