### ISSUE TITLE
Date and time menus don't lose focus on select

### ISSUE THREAD

**Issue by cat-bro** [bor3ham/mireco#4]
Using datetime-range, if you select a date from the calendar you have to click outside the calendar to make it disappear, this also happens when selecting a time from the menu.
I'd change the line
```this.textRef.current && this.textRef.current.focus()```
to
```this.setState({inFocus: false})```

in the select handlers of both `src/forms/date.js` and `src/forms/time.js`

**Comment by bor3ham** [comment]
I know this is an old one but this is fixed as of 0.0.15
I'll be updating workforce with the new version soon!
